services:
  api:
    # Where is the Dockerfile for this service?
    # build: ...

    # Which ports on this computer should forward into the container?
    # ports:
    #   - "HOST_PORT:CONTAINER_PORT"

    environment:
      # Keep the database outside the code folder. (We'll see why later.)
      DB_PATH: /data/todos.db

    # What folders from this computer should the container be able to see?
    # volumes:
    #   - ...

  # ui:
  #   ...

# Named volumes: storage that Docker manages and keeps between runs
# volumes:
#   ...
