# Start from a base image that already has Python installed
# See base images here
# https://hub.docker.com/_/python

# FROM ...

# Pick a folder inside the container to hold our code
# WORKDIR ...

# Copy our code from this computer into the image
# COPY ...

# Install our Python dependencies
# RUN ...

# The command that starts the app when the container runs
# CMD ...
